DROP DATABASE IF EXISTS week6_jdbc;
CREATE DATABASE week6_jdbc DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE week6_jdbc;

DROP TABLE IF EXISTS student;
CREATE TABLE student (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    student_no VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    major VARCHAR(80) NOT NULL,
    grade INT NOT NULL,
    phone VARCHAR(30),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
